import './main.sass'

import './components/dropdown/dropdown'
import './components/checkbox_list/checkbox_list'
import './components/pagination/pagination'
import './components/like-button/like-button'
import './components/comment/comment'
import './components/caption/caption'
import './components/text-field/text-field'
import './components/button/button'
import './components/login/login'

// import './svg/smile.svg'
// import './svg/home.svg'
// import './components/logo/img/full_logo.svg'
// import  './components/logo/img/logo.svg'
// import './components/footer/img/twitter.svg'
// import './components/footer/img/facebook.svg'
// import './components/footer/img/instagram.svg'
import './img/favicon.png'
import './components/comment/img/avatar-murad.png'